version:2

jobs:
  build:
    docker:
      - image: cimg/node:16.18.0
    branches:
      only:
        - main 
    steps:
      - run:
          name: Install
          command: console.log('Install...')
      - run:
          name: Test
          command: console.log('Testing...')    
      - checkout # 从github拉取代码
      # 使用缓存    
