version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.18.0
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'e7:9c:16:08:4f:6e:ed:8a:d9:9b:2a:4c:e0:fb:e7:c7'
      - checkout # 从github拉取代码
      # 使用缓存
      - restore_cache:
          key: node-dependence
      - run:
          name: Install
          command: yarn install
      # 设置缓存
      - save_cache:
          key: node-dependence
          paths:
            - node_modules
      - run:
          name: build
          command: yarn build
