version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.18.0
    branches:
      only:
        - main
    steps:
      - run:
          name: Install
          command: echo "1"
      - run:
          name: Test
          command: echo "2"
      - checkout # 从github拉取代码
      # 使用缓存
