version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.18.0
    branches:
      only:
        - main
    working_directory: /app
    steps:
      - run: echo "===================构建开始==================="
      # - add_ssh_keys:
      #     fingerprints:
      #       - '8b:2e:7c:f7:dc:fc:60:0e:b1:3b:c7:cd:e1:12:3e:e0'
      - checkout # 从github拉取代码
      # 使用缓存
      - restore_cache:
          key: node-dependence
      - run:
          name: Install
          command: yarn install
      # 设置缓存
      - save_cache:
          key: node-dependence
          paths:
            - node_modules
      - run:
          name: Build
          command: yarn build
      - run: echo "===================构建结束==================="
  deploy:
    steps:
      - run: echo "===================部署开始==================="
      # 如果出现权限问题，请加上权限设置任务，给脚本添加执行权限，然后再执行发布任务
      - run:
          name: AuthSet
          command: chmod +x circleci-deploy.sh
      - run:
          name: Deploy
          command: sh circleci-deploy.sh
      - run: echo "===================部署结束==================="
