version: 2.1
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_IP "echo 'hello'"

workflows:
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main # only deploy on the main branch
