version: 2
jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.18.0
    working_directory: ~/circleci-demo
    steps:
      - run: echo "===================构建开始==================="
      - checkout # 从github拉取代码
      # 使用缓存
      - restore_cache:
          key: node-dependence
      - run:
          name: Install
          command: yarn install
      # 设置缓存
      - save_cache:
          key: node-dependence
          paths:
            - node_modules
      - run:
          name: Build
          command: ls -a && yarn build
      - run: echo "===================构建结束==================="
      - run: echo "===================Github Pages部署开始==================="
      # 如果出现权限问题，请加上权限设置任务，给脚本添加执行权限，然后再执行发布任务
      - run:
          name: AuthSet
          command: chmod +x gh-deploy.sh
      - run:
          name: Deploy
          command: sh gh-deploy.sh
      - run: echo "===================Github Pages部署结束==================="
  deploy-prod:
    machine:
      enable: true
    working_directory: ~/circleci-demo-deploy
    steps:
      - run: echo "===================远程服务器部署开始==================="
      - add_ssh_keys:
          fingerprints:
            - 'd0:90:a1:ba:04:47:95:c8:ed:c3:e1:70:77:7a:01:bf'
      - run:
          name: Adding known host
          command: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run:
          name: Copy dist to ssh server
          # command: touch vite.config.ts && ls -a && scp -r . $SSH_USER@$SSH_IP:~/data/vue-demo/
          command: git remote -v
      - run: echo "===================远程服务器部署结束==================="
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
      - deploy-prod:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
